//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using MGame.Base;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

//数据配置管理
public class ConfigManager:Singleton<ConfigManager>
{
	private Dictionary<int,SkillConfig> skillConfigs;

	private Dictionary<int,HeroConfig> heroConfigs;

	private Dictionary<int,ScenarioConfig> scenarioConfigs;

	protected ConfigManager ()
	{
		skillConfigs = new Dictionary<int, SkillConfig> ();
		heroConfigs = new Dictionary<int, HeroConfig> ();
		scenarioConfigs = new Dictionary<int, ScenarioConfig> ();
	}

	public void load()
	{


	}
}


