//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

//英雄配置
public class HeroConfig
{
	//英雄ID
	public int HeroId{ get; set;}
	//名称
	public string HeroName{ get; set;}
	//血量	
	public int Hp{ get; set;}
	//攻击
	public int Atk{ get; set;}
	//防御
	public int Def{ get; set;}
	//品质
	public int Quality{ get; set;}
	//星级
	public int Star{ get; set;}
	//类型
	public int Type{ get; set;}
	//图片资源前缀
	public string ImgPrefix{ get; set;}
	//武将技能
	public int SkillId{ get; set;}
}



