//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
//技能配置
public class SkillConfig
{
	public int SkillId{ get; set;}
	public string SkillName{ get; set;}
	//技能类型 
	public int Type{ get; set;}
	//技能伤害
	public int Hurt{ get; set;}
	//飞行动画
	public string FlyPrefab{ get; set;}
	// 命中动画
	public string HitPrefab{ get; set;}
}


